### ISSUE TITLE
[1.8.9] Server Crash when creating a dimension (conflict with SpongeForge?)

### ISSUE THREAD

**Issue by Xiaminou** [lumien231/Simple-Dimensions#3]
Crash Report: http://pastebin.com/w8D4wk7P

**Comment by lumien231** [comment]
I don't know whether it's a conflict with SpongeForge but it looks like it, so does this also happen when you aren't using SpongeForge?

**Comment by Xiaminou** [comment]
No it doesn't happen without SpongeForge, but I don't think it's a conflict. The client crash upon entering the dimension so obviously something's wrong.

**Comment by lumien231** [comment]
Ehh? This is a server crash you reported.

**Comment by Xiaminou** [comment]
#4

**Comment by lumien231** [comment]
Yes but i'm talking about #3 :)

**Comment by Xiaminou** [comment]
Yes but one would assume that they're linked, I doubt it's a coincidence.

**Comment by lumien231** [comment]
I knew about #3 already, it is an intermod thing and doesn't happen anymore in the 1.9 version. So you might have to wait till you switch to 1.9 to use SimpleDimensions.

For the other issue i'll have to wait till SpongeForge is available for 1.9.4 to see whether it still happens or not.

**Comment by Xiaminou** [comment]
humm, okay... I kinda would have liked to have a void world to save FPS/TPS but I guess that's just not going to happen.

**Comment by lumien231** [comment]
You could maybe use RFTools Dimension.

**Comment by Xiaminou** [comment]
https://github.com/McJty/RFTools/issues/539
